unless Vagrant.has_plugin?("vagrant-disksize")
  raise 'vagrant-disksize is not installed! Run vagrant plugin install vagrant-disksize and relauch your punchbox command'
end

unless Vagrant.has_plugin?("vagrant-vbguest")
  raise 'vagrant-vbguest is not installed! Run vagrant plugin install vagrant-vbguest and relauch your punchbox command'
end

Vagrant.configure("2") do |config|

  # Auto install required Vagrant plugins
  config.vagrant.plugins = ["vagrant-disksize"]
  
  # Get your local SSH public key
  PUBLIC_KEY = File.read("#{Dir.home}/.ssh/id_rsa.pub")

  # Speed up VM creation using a precompiled '.vdi'
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

    # CENTRAL-FRONT-1 : 
    config.vm.define "central-front-1" do |server|
      server.vm.box = "generic/centos8"
      server.vm.box_check_update = false
      config.disksize.size = '30GB'

      # Share only sample_confs
      # Point to your configuration folder to update conf directly on deployed punchplatform
      # TODO : change configuration folder
      # TODO : uncomment after vagrant up + deploy operator
      # TODO : run vagrant reload to take into account
      server.vm.synced_folder '.', '/vagrant', disabled: true
      #server.vm.synced_folder '/home/francoisguibourt/git/onesky/central-conf', '/home/punch-operator/central-conf', :owner => 'punch-operator', :group => 'punch-operator', create: false

      ## Configuration
      server.vm.hostname = "central-front-1"
      server.vm.network "private_network", ip: "172.28.128.31"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/central-front-1/d' /etc/hosts"
      server.vm.provision "shell", inline: "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.41 central-back-1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.42 central-back-2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.31 central-front-1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.32 central-front-2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.21 collector-1' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 6144
        v.cpus = 2
      end
    end

    # CENTRAL-FRONT-2 : 
    config.vm.define "central-front-2" do |server|
      server.vm.box = "generic/centos8"
      server.vm.box_check_update = false
      config.disksize.size = '30GB'

      # Share only sample_confs
      # Point to your configuration folder to update conf directly on deployed punchplatform
      server.vm.synced_folder '.', '/vagrant', disabled: true

      ## Configuration
      server.vm.hostname = "central-front-2"
      server.vm.network "private_network", ip: "172.28.128.32"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/central-front-2/d' /etc/hosts"
      server.vm.provision "shell", inline: "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.41 central-back-1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.42 central-back-2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.31 central-front-1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.32 central-front-2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.21 collector-1' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 6144
        v.cpus = 2
      end
    end

    # CENTRAL-BACK-1
    config.vm.define "central-back-1" do |server|
      server.vm.box = "generic/centos8"
      server.vm.box_check_update = false
      config.disksize.size = '30GB'

      # Share only sample_confs
      # Point to your configuration folder to update conf directly on deployed punchplatform
      # TODO : change configuration folder
      # TODO : uncomment after vagrant up + deploy operator
      # TODO : run vagrant reload to take into account
      server.vm.synced_folder '.', '/vagrant', disabled: true
      #server.vm.synced_folder '/home/francoisguibourt/git/onesky/central-conf', '/home/punch-operator/central-conf', :owner => 'punch-operator', :group => 'punch-operator', create: false

      ## Configuration
      server.vm.hostname = "central-back-1"
      server.vm.network "private_network", ip: "172.28.128.41"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/central-back-1/d' /etc/hosts"
      
      server.vm.provision "shell", inline: "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.41 central-back-1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.42 central-back-2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.31 central-front-1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.32 central-front-2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.21 collector-1' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 6144
        v.cpus = 2
      end
    end

    # CENTRAL-BACK-2
    config.vm.define "central-back-2" do |server|
      server.vm.box = "generic/centos8"
      server.vm.box_check_update = false
      config.disksize.size = '30GB'

      # Share only sample_confs
      # Point to your configuration folder to update conf directly on deployed punchplatform
      # TODO : change configuration folder
      # TODO : uncomment after vagrant up + deploy operator
      # TODO : run vagrant reload to take into account
      server.vm.synced_folder '.', '/vagrant', disabled: true
      #server.vm.synced_folder '/home/francoisguibourt/git/onesky/central-conf', '/home/punch-operator/central-conf', :owner => 'punch-operator', :group => 'punch-operator', create: false

      ## Configuration
      server.vm.hostname = "central-back-2"
      server.vm.network "private_network", ip: "172.28.128.42"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/central-back-2/d' /etc/hosts"
      server.vm.provision "shell", inline: "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.41 central-back-1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.42 central-back-2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.31 central-front-1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.32 central-front-2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.21 collector-1' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 6144
        v.cpus = 2
      end
    end

end
