version: '6.0'
type: punchline
runtime: storm

dag:
  - type: kafka_input
    settings:
      topic: validation_archive_housekeeping
      start_offset_strategy: last_committed
      exit_conditions:
        success:
          acks_greater_or_equal_to: 20
          require_no_remaining_tuple_to_inject: true
          require_no_pending_tuple: true
        failure:
          fails_greater_or_equal_to: 1
    publish:
      - stream: logs
        fields:
          - log
          - _ppf_timestamp
          - age
          - _ppf_partition_id
          - _ppf_partition_offset

  - type: file_output
    settings:
      destination: file:///tmp/archive_housekeeping/storage
      create_root: true
      compression_format: gzip
      batch_size: 10
      fields:
        - _ppf_timestamp
        - log
        - age
      tags:
        - age
      timestamp_field: _ppf_timestamp
    subscribe:
      - component: kafka_input
        stream: logs
    publish:
      - stream: metadatas
        fields:
          - metadata

  - type: elasticsearch_output
    component: metadatas_indexer
    settings:
      per_stream_settings:
        - stream: metadatas
          index:
            type: constant
            value: validation-archive-housekeeping
          document_json_field: metadata
      batch_size: 1
      reindex_failed_documents: true
      error_index:
        type: constant
        value: validation-archive-housekeeping-errors
    subscribe:
      - component: file_output
        stream: metadatas

settings:
  topology.worker.childopts: -server -Xms256m -Xmx256m
