unless Vagrant.has_plugin?("vagrant-disksize")
  raise 'vagrant-disksize is not installed! Run vagrant plugin install vagrant-disksize and relauch your punchbox command'
end

unless Vagrant.has_plugin?("vagrant-vbguest")
  raise 'vagrant-vbguest is not installed! Run vagrant plugin install vagrant-vbguest and relauch your punchbox command'
end

Vagrant.configure("2") do |config|

  # Auto install required Vagrant plugins
  config.vagrant.plugins = ["vagrant-disksize"]
  
  # Get your local SSH public key
  PUBLIC_KEY = File.read("#{Dir.home}/.ssh/id_rsa.pub")

  # Speed up VM creation using a precompiled '.vdi'
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

   config.vm.define "server1" do |server|
      server.vm.box = "eurolinux-vagrant/centos-7"
      
      server.vm.box_check_update = false
      config.disksize.size = '40GB'

      # Share only sample_confs
      server.vm.synced_folder '.', '/vagrant', disabled: true
      server.vm.synced_folder '/tmp/archive-log/storage', '/tmp/archive-logs/storage', create: true
      ## Configuration
      server.vm.hostname = "server1"
      server.vm.network "private_network", ip: "172.28.128.21"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/server1/d' /etc/hosts"
      server.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.21 server1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.22 server2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.23 server3' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.24 server4' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.25 server5' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 3072
        v.cpus = 2
      end

      #To unregister the VM from the redhat developer account

    end

   config.vm.define "server2" do |server|
      server.vm.box = "eurolinux-vagrant/centos-7"
      
      server.vm.box_check_update = false
      config.disksize.size = '40GB'

      # Share only sample_confs
      server.vm.synced_folder '.', '/vagrant', disabled: true
      server.vm.synced_folder '/tmp/archive-log/storage', '/tmp/archive-logs/storage', create: true
      ## Configuration
      server.vm.hostname = "server2"
      server.vm.network "private_network", ip: "172.28.128.22"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/server2/d' /etc/hosts"
      server.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.21 server1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.22 server2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.23 server3' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.24 server4' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.25 server5' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 3072
        v.cpus = 2
      end

      #To unregister the VM from the redhat developer account

    end

   config.vm.define "server3" do |server|
      server.vm.box = "eurolinux-vagrant/centos-7"
      
      server.vm.box_check_update = false
      config.disksize.size = '40GB'

      # Share only sample_confs
      server.vm.synced_folder '.', '/vagrant', disabled: true
      server.vm.synced_folder '/tmp/archive-log/storage', '/tmp/archive-logs/storage', create: true
      ## Configuration
      server.vm.hostname = "server3"
      server.vm.network "private_network", ip: "172.28.128.23"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/server3/d' /etc/hosts"
      server.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.21 server1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.22 server2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.23 server3' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.24 server4' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.25 server5' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 8024
        v.cpus = 2
      end

      #To unregister the VM from the redhat developer account

    end

   config.vm.define "server4" do |server|
      server.vm.box = "eurolinux-vagrant/centos-7"
      
      server.vm.box_check_update = false
      config.disksize.size = '40GB'

      # Share only sample_confs
      server.vm.synced_folder '.', '/vagrant', disabled: true
      server.vm.synced_folder '/tmp/archive-log/storage', '/tmp/archive-logs/storage', create: true
      ## Configuration
      server.vm.hostname = "server4"
      server.vm.network "private_network", ip: "172.28.128.24"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/server4/d' /etc/hosts"
      server.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.21 server1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.22 server2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.23 server3' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.24 server4' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.25 server5' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 6144
        v.cpus = 2
      end

      #To unregister the VM from the redhat developer account

    end

   config.vm.define "server5" do |server|
      server.vm.box = "eurolinux-vagrant/centos-7"
      
      server.vm.box_check_update = false
      config.disksize.size = '40GB'

      # Share only sample_confs
      server.vm.synced_folder '.', '/vagrant', disabled: true
      server.vm.synced_folder '/tmp/archive-log/storage', '/tmp/archive-logs/storage', create: true
      ## Configuration
      server.vm.hostname = "server5"
      server.vm.network "private_network", ip: "172.28.128.25"

      ## Provisionning
      server.vm.provision "shell", inline: <<-EOF
        echo 'export LC_ALL=C' >> ~/.bashrc
        echo '#{PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      EOF
      server.vm.provision "shell", inline: "echo 'tmpfs /tmp tmpfs size=4g 0 0' >> /etc/fstab"

      # Disabling SElinux
      server.vm.provision "shell", inline: "sudo sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config"
      server.vm.provision "shell", inline: "sudo setenforce 0"

      # Disabling firewalld
      server.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      server.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      server.vm.provision "shell", inline: "sudo systemctl mask --now firewalld"

      server.vm.provision "shell", inline: "sed -i '/server5/d' /etc/hosts"
      server.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
      server.vm.provision "shell", inline: "echo '172.28.128.21 server1' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.22 server2' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.23 server3' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.24 server4' >> /etc/hosts"
      server.vm.provision "shell", inline: "echo '172.28.128.25 server5' >> /etc/hosts"

      server.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 3072
        v.cpus = 2
      end

      #To unregister the VM from the redhat developer account

    end
end